# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: assetflow_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    # MUDAR AQUI: Use 'sh -c' em vez de 'bash -c'
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails db:create db:migrate && rails server -b 0.0.0.0 -p 3000"
    volumes:
      - ./backend:/app
      - bundle_data:/usr/local/bundle
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/assetflow_development
      RAILS_ENV: development

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_BASE_URL: http://backend:3000/api/v1
    depends_on:
      - backend

volumes:
  postgres_data:
  bundle_data: